spring.application.name=stockManagement

# 데이터베이스 설정 (로컬 PostgreSQL)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=stock
spring.datasource.username=postgres
spring.datasource.password=0915

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.validation-timeout=5000

# JPA 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=stock
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.use_sql_comments=false

# 서버 포트 설정
server.port=8080


naver.commerce.client-id=${NAVER_CLIENT_ID:}
naver.commerce.client-secret=${NAVER_CLIENT_SECRET:}
naver.commerce.api-base-url=https://api.commerce.naver.com/external


cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}

aes.key=0123456789abcdef0123456789abcdef


spring.servlet.multipart.enabled=true
# 파일 업로드 설정
spring.servlet.multipart.max-file-size=1024MB
spring.servlet.multipart.max-request-size=1024MB

# JSON 직렬화 오류 방지
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.parameter-names-module=true

# JSON 중첩 깊이 한도 조정
spring.jackson.stream-write-constraints.max-nesting-depth=2000
